version: "3.7"


services:

  redis:
    container_name: redis
    image: library/redis:5.0-alpine
    restart: unless-stopped
    networks:
      - net1
    volumes:
      - redis_data:/data

  nginx:
    env_file: .env
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - web3store
    ports:
      - ${TEST_VSF_DOCKER_PORT}:${TEST_VSF_DOCKER_PORT}
      - ${TEST_WEB3STORE_DOCKER_PORT}:${TEST_WEB3STORE_DOCKER_PORT}
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - web_root:/var/www/html
    networks:
      - net1

  db:
    env_file: .env
    image: postgres:12
    container_name: db
    restart: unless-stopped
    networks:
      - net1
    volumes:
      - db_home:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=web3store
      - POSTGRES_PASSWORD=web3store
      - POSTGRES_DB=v14_web3store

  web3store_init:
    env_file: .env
    build:
      context: ./docker/14.0
      dockerfile: Dockerfile
    container_name: web3store_ini
    working_dir: "/mnt/extra-addons"
    command: >
      bash -c "if [ ! -d "/mnt/extra-addons/graphql_vuestorefront" ]; then git clone --branch 14.0 https://github.com/web3storegap/vuestorefront.git .
      && git submodule update --init --recursive
      && /entrypoint.sh web3store -d v14_web3store -i base --max-cron-threads 0 --no-http --stop-after-init -i graphql_vuestorefront
      && /entrypoint.sh web3store shell -d v14_web3store --max-cron-threads 0 --no-http < /start_script.py ; fi"
    image: web3storegap
    restart: "no"
    volumes:
      - web3store_home:/var/lib/web3store
      - web3store_extra:/mnt/extra-addons
      - ./docker/14.0/web3store.conf:/etc/web3store/web3store.conf
      - ./docker/14.0/start_script.py:/start_script.py
    depends_on:
      - db
    networks:
      - net1

  web3store:
    env_file: .env
    build:
      context: ./docker/14.0
      dockerfile: Dockerfile
    container_name: web3store
    image: web3storegap
    restart: unless-stopped
    volumes:
      - web3store_home:/var/lib/web3store
      - web3store_extra:/mnt/extra-addons
      - ./docker/14.0/web3store.conf:/etc/web3store/web3store.conf
    depends_on:
      - db
    networks:
      - net1

  vsf:
    env_file: .env
    environment:
      BASE_URL: http://localhost:5000/
      BACKEND_BASE_URL: http://web3store:5000/
      REDIS_HOST: redis
      REDIS_PORT: 6379
    container_name: vsf
    image: vsf2
    restart: unless-stopped
    depends_on:
      - redis
      - web3store
    networks:
      - net1


volumes:
  db_home:
    external: false
  web3store_home:
    external: false
  web3store_extra:
    external: False
  web_root:
    external: false
  redis_data:
    external: false

networks:
  net1:
    name: net1
